"""rich text posts

Revision ID: c6425f2d56dc
Revises: 6db1cd64fe3e
Create Date: 2020-08-19 12:08:57.039093

"""

# revision identifiers, used by Alembic.
revision = 'c6425f2d56dc'
down_revision = '6db1cd64fe3e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    # ### end Alembic commands ###
