"""account confirmation

Revision ID: d9b01c4651db
Revises: d606fb50218b
Create Date: 2020-08-17 14:56:36.574109

"""

# revision identifiers, used by Alembic.
revision = 'd9b01c4651db'
down_revision = 'd606fb50218b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    # ### end Alembic commands ###
